### ISSUE TITLE
Nomenclature compatibility with ModSpec: Abstract test vs Conformance test

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/AutomatedDocumentation#10]
Not sure whether this is too late, but is a nomenclature difference between the latest diagram and OGC ModSpec.

Diagram here for reference:
![image](https://user-images.githubusercontent.com/11865/143399347-a7c01ed1-128e-4139-afa9-354a9ea79499.png)

In OGC, an Abstract Test is just a Conformance Test.

In ModSpec, there are only these models:
* Conformance Test
* Conformance Class (= multiple conformance tests)
* Conformance Suite (= multiple conformance classes)

An "Abstract Test" is actually just a "Conformance Test" with an attribute of `abstract` set to true. The name of "Abstract Test" differs from "Conformance Test" only for convenience.

In the current diagram, it defines:
* Abstract Test Case
* Conformance Class
* Abstract Test Suite

I find this nomenclature rather confusing, i.e.
* ISO/TC 211 standards cannot have "non-abstract test cases"?

**Comment by jetgeo** [comment]
As long as I have been involved in ISO/TC 211, standards have always had an Annex A - Abstract Test Suite.
However, I agree that conformance suite and conformance test are better names. 

Perhaps @MatsAhlin or @PeterParslow has some thoughts?

**Comment by PeterParslow** [comment]
It's an "abstract test suite" as opposed to an "executable test suite", not because it tests abstract things. An executable test suite is an instantiation (realisation?) of the abstract test suite in a particular technology. As ISO 19105 puts it (text for FDIS): "An abstract test case is used as the basis for generating an executable test case and is independent of the IUT" implementation under test.

For example, in ISO/CD 19115-3 we say "ISO 19115-1 and 19115-2 provide Abstract Test Suites; this document defines an Executable Test Suite for XML implementations." (although we're thinking of changing it to "this document provides XML schema documents and Schematron rules to facilitate an Executable Test Suite implementing those Abstract Test Suites" - to support the various use cases of community profiles & extensions.

On reflection, I wonder if ISO 19105 is helpful in using the word "abstract" for each of the things in the ATS: abstract test case, abstract test module, abstract test method. I guess it's consistent.

**Comment by jetgeo** [comment]
Closing this issue, suggest further discussions in an NWIP for Modular Specs.
