### ISSUE TITLE
The attribute IdentifiedObject.text

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/AutomatedDocumentation#4]
As discussed at the meeting today: 
We have identified a challenge with the implementation of the attribute `IdentifiedObject.text` as a tagged value in the UML Profile. A tagged value can only contain 255 characters, and the text of several requirements from ISO 19131 are longer than that. 
@heidivanparys referred to a workaround from Sparx, described at https://www.sparxsystems.com/enterprise_architect_user_guide/15.2/automation/taggedvalue.html

My understanding of the description is that the text `<memo>` as a tagged value does not change the limits for the tagged value, it simply tells the user of the model to read the ‘Notes’ attribute for the tagged value instead. If this is correct, one will need to include an extra control of which attribute to use. Besides, it does not seem to be possible to show the content of the ‘Note’ attribute for a tagged value in diagrams. Only the <memo> value appears. For the users, the requirements text will then be quite hidden. I think that for the specific tagged value in question (‘text’), it would be better to use the ‘Notes’ field of the class. 
See the example below with a very long requirement text from ISO 19131.

Comments?

![image](https://user-images.githubusercontent.com/7501876/118993265-a978fe80-b985-11eb-8dcc-99a41ff0f3d1.png)

**Comment by heidivanparys** [comment]
I can see the point with the text not showing up, so yes, I agree, in this case the Notes field is probably the better option indeed.

My main concern is the use of the Notes fields in other types of models – models used to create data dictionaries e.g., see https://github.com/orgs/ISO-TC211/teams/adhoc-automated-documentation/discussions/9 – where the Notes field includes definition and notes and examples and source and .... So different things, see e.g. https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/index.htm?goto=2:1:1:1:7074. Terminology best practice says those should be clearly separated, and it is easier to develop tooling to assist filling out those things - and easier to avoid mistakes by editors! - when tags are used there. We don't have a practice for showing those kinds of information on diagrams, do we?

So a guideline could be: if you have long texts that are part of the model elements:

- put them in tagged values if they are not used on diagrams but output to other representations of the model
- put them in the Notes field if they are used on diagrams

Note: I am not totally against using Notes 🙂, I used them e.g. recently for describing diagrams, there it also makes sense to use Notes and not tagged values, because then you can actually add links to elements of the model, see also the comments on https://github.com/orgs/ISO-TC211/teams/adhoc-automated-documentation/discussions/7.

**Comment by magnusKarge** [comment]
+1 for using the "Notes" field for text in normative statements

**Comment by ronaldtse** [comment]
I understand the concern of @heidivanparys that:
- we want to annotate the model objects (classes, attributes, associations etc) with different types of content. Including descriptions, notes and examples. 
- the notes field provides generic rich text functionality but without ability to enforce or tag structured content (ie. Identify different types of contents) 

Given the limitation of tagged value length described by @jetgeo , we can’t really accommodate the full text of these different types of content into the tagged value. 

The easier solution here is to enforce the usage of the Notes field into a structured data field:
- treat the notes field as a plain text field (as recommended by @heidivanparys during chat of the last meeting)
- Use a rich text encoding method for the notes field like AsciiDoc or Markdown, whose syntax can be validated  
- Express the text encoding of the notes field in the notes field itself

What do you think?
