### ISSUE TITLE
Handling of complex requirements

### ISSUE THREAD

**Issue by jetgeo** [ISO-TC211/AutomatedDocumentation#8]
Some standards, such as the draft [ISO 19123-3](https://github.com/ISO-TC211/AutomatedDocumentation/files/7224380/ISO_19123-3_2021-09-01.pdf) contains complex requirements with formulas etc. Can such requirements be handled in a model of requirements?

**Comment by ronaldtse** [comment]
The OGC ModSpec models implemented in Metanorma support complex / rich text content within them. 

The models of Requirement, Requirements Class, Conformance Test (and Abstract Test), Conformance Class are supported, allowing parts and recursive steps. 

If the complexity is at the level of the requirements model, then we’ll have to investigate further.

**Comment by jetgeo** [comment]
The complexity I am referring to here is that the requirement itself is formulated as a long and formatted text with formulas etc. This is not really fit for writing as notes in a UML model....
For example: 
![image](https://user-images.githubusercontent.com/7501876/135235792-9c3fa35a-2b93-4e4a-8762-5af1f96baabb.png)

**Comment by ronaldtse** [comment]
@jetgeo we can certainly fit this content into the Metanorma encoding (unless this should go into EA), it will generate fine. The only issue is that the content won't be very machine-readable due to the rather arbitrary structure.

In the PDF, apparently a requirement can contain multiple Lets, Thens and Ands. Is this the model desired by ISO/TC 211 for a Requirement (or a specialised "math" requirement), or is this only of a passing interest?

* If it is to be supported, we can make this machine-readable given a formal model
* If not, we can just encode this content as rich text within a requirement but the content won't be very machine-readable.

**Comment by PeterParslow** [comment]
Related question: PMG, in drafting "good practice on document style" would like to know the AHG8 & the Resource Group's view on whether it is acceptable for a single identified requirement to contain multiple sentences (or phrases) containing the word "shall". I sent AG3 (PMG)'s N264 to @jetgeo and @ReesePlews on 13 September, hoping for a response in time for PMG (i.e. by November). I attach it here, for interest.

[Towards a TC211 good practice on document style.docx](https://github.com/ISO-TC211/AutomatedDocumentation/files/7302450/Towards.a.TC211.good.practice.on.document.style.docx)
It is the presence of "shall" that makes as a statement a requirement (in ISO terms), so this is effectively asking whether we (TC211) are happy that one requirement identifier (URI) identifies a cluster of closely related requirements.
